CREATE TABLE IF NOT EXISTS dm_peer_state(peer TEXT PRIMARY KEY, revision TEXT NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS dm_seen_events(id TEXT PRIMARY KEY, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS dm_replies(message_id TEXT PRIMARY KEY, peer TEXT NOT NULL, revision TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL, updated INTEGER NOT NULL, sent_id TEXT);
