CREATE TABLE IF NOT EXISTS social_jobs (
 id TEXT PRIMARY KEY, slot TEXT NOT NULL UNIQUE, kind TEXT NOT NULL,
 category TEXT NOT NULL, caption TEXT NOT NULL, due INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'scheduled', asset_id TEXT NOT NULL,
 container_id TEXT, media_id TEXT, permalink TEXT, error TEXT,
 created INTEGER NOT NULL, updated INTEGER NOT NULL, published INTEGER
);
CREATE TABLE IF NOT EXISTS social_assets(id TEXT PRIMARY KEY, bytes BLOB NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS social_events(id INTEGER PRIMARY KEY AUTOINCREMENT, job_id TEXT, kind TEXT NOT NULL, note TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS social_snapshots(id TEXT PRIMARY KEY, body TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS social_leases(id TEXT PRIMARY KEY, until_at INTEGER NOT NULL);
