import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {socialAction,socialTick,validateJob,slotFor,socialAsset} from './social.mjs';import worker from './worker.mjs';
import {studioAction} from './studio.mjs';
function env(){const db=new DatabaseSync(':memory:');for(const name of ['schema.sql','social.sql'])db.exec(readFileSync(new URL(name,import.meta.url),'utf8'));const DB={prepare(sql){let args=[];return{bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return{results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}};}};},async batch(s){db.exec('BEGIN');try{const results=[];for(const x of s)results.push(await x.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};return {db,DB,APP_ORIGIN:'https://example.test',IG_ACCESS_TOKEN:'test-token',IG_ACCOUNT_ID:'test-id',OWNER_PASSWORD:'owner',DATA_ENCRYPTION_KEY:'ab'.repeat(32)};}
const due=Date.parse('2026-10-01T16:00:00+09:00'),now=due-3600000;
const jpeg=Buffer.concat([Buffer.from([255,216,255]),Buffer.alloc(1200)]).toString('base64');
const payload=()=>({kind:'feed',category:'求人',caption:'仕事内容はプロフィールのメッセージから聞いてください。',due,jpeg,checked:true});
test('複数ストーリーは順番を守り、結果不明の後続を公開しない',async()=>{const e=env();active(e);const d=due-5*3600000,n=d-2*3600000,p={...payload(),kind:'story',due:d};await assert.rejects(()=>socialAction(e,'/api/social/queue',{...p,frame:2},n));for(const frame of [1,2,3])await socialAction(e,'/api/social/queue',{...p,frame},n);await assert.rejects(()=>socialAction(e,'/api/social/queue',{...p,frame:2},n));e.db.prepare("UPDATE social_jobs SET status='ready',container_id=slot").run();let order=[];const f=globalThis.fetch;globalThis.fetch=async(url,o)=>{order.push(new URLSearchParams(o.body).get('creation_id'));if(order.length===2)throw Error('connection lost');return Response.json({id:'m1'});};try{await socialTick(e,new Date(d));assert.deepEqual(order,['2026-10-01:story','2026-10-01:story:02']);assert.deepEqual(e.db.prepare('SELECT status FROM social_jobs ORDER BY slot').all().map(x=>x.status),['published','uncertain','ready']);}finally{globalThis.fetch=f;}});
test('予報待ち下書きは公開せず、検品済み編集で予約へ切り替える',async()=>{const e=env();active(e);const j=await socialAction(e,'/api/social/queue',{...payload(),hold:true},now-3600000);let calls=0;const f=globalThis.fetch;globalThis.fetch=async()=>{calls++;return Response.json({id:'c'});};try{await socialTick(e,new Date(due-5400000));assert.equal(calls,0);await socialAction(e,'/api/social/edit',{...payload(),id:j.id},now);assert.equal(e.db.prepare('SELECT status FROM social_jobs').get().status,'scheduled');await assert.rejects(()=>socialAction(e,'/api/social/edit',{...payload(),id:j.id,kind:'story',due:due-5*3600000},now-6*3600000));}finally{globalThis.fetch=f;}});
test('スマホ制作は一日6回まで、下書き保存で公開予約は作られない',async()=>{const e=env();let calls=0;e.AI={async run(model,p){assert.equal(model,'@cf/black-forest-labs/flux-1-schnell');assert.equal(p.steps,4);calls++;return {image:jpeg};}};const results=await Promise.all(Array.from({length:6},()=>studioAction(e,'generate',{brief:'a yellow tape measure'},now)));await assert.rejects(()=>studioAction(e,'generate',{brief:'another image'},now));assert.equal(calls,6);const d=await studioAction(e,'save',{kind:'story',category:'求人',headline:'まずは話から',caption:'質問だけでもお気軽に',asset:results[0].asset},now);assert.equal((await studioAction(e,'drafts',{},now)).drafts[0].id,d.draft.id);assert.equal(e.db.prepare('SELECT COUNT(*) n FROM social_jobs').get().n,0);assert.equal((await worker.fetch(new Request(e.APP_ORIGIN+'/api/studio/drafts'),e)).status,401);await assert.rejects(()=>studioAction(e,'save',{kind:'story',category:'求人',asset:'a'.repeat(48)},now));});
test('画像確認中の取消競合を防ぎ、確認後の取消を保持する',async()=>{const e=env();const j=await socialAction(e,'/api/social/queue',payload(),now);const f=globalThis.fetch;globalThis.fetch=async()=>{await assert.rejects(()=>socialAction(e,'/api/social/cancel',{id:j.id},now));return Response.json({id:'c'});};try{assert.equal((await socialAction(e,'/api/social/prepare',{id:j.id},now)).status,'processing');await socialAction(e,'/api/social/cancel',{id:j.id},now);assert.equal(e.db.prepare('SELECT status FROM social_jobs').get().status,'cancelled');}finally{globalThis.fetch=f;}});
function active(e){e.db.prepare('INSERT INTO meta VALUES(?,?)').run('socialMode','active');e.db.prepare('INSERT INTO meta VALUES(?,?)').run('socialLastInsights',String(now));}
test('日本時間の予約枠、画像・文言・検品を検証する',()=>{assert.equal(slotFor('feed',due),'2026-10-01:feed');assert.equal(validateJob(payload(),now).kind,'feed');for(const change of [{due:now},{due:due+3600000},{kind:'story'},{checked:false},{jpeg:'abc'},{caption:'https://ig.me/m/test'}])assert.throws(()=>validateJob({...payload(),...change},now));});
test('同日の同種別を二重登録せず、画像URLは推測困難な識別子のみ',async()=>{const e=env();await socialAction(e,'/api/social/queue',payload(),now);await assert.rejects(()=>socialAction(e,'/api/social/queue',payload(),now));const job=e.db.prepare('SELECT * FROM social_jobs').get();assert.equal(job.asset_id.length,48);assert.equal((await socialAsset(e,'/social-media/'+job.asset_id+'.jpg')).status,200);assert.equal(await socialAsset(e,'/social-media/1.jpg'),null);});
test('停止中は投稿せず、再開後も予定時刻前に公開しない',async()=>{const e=env();await socialAction(e,'/api/social/queue',payload(),now);e.db.prepare('INSERT INTO meta VALUES(?,?)').run('socialLastInsights',String(now));let calls=0;const f=globalThis.fetch;globalThis.fetch=async()=>{calls++;return Response.json({id:'container'});};try{await socialTick(e,new Date(due-1800000));assert.equal(calls,0);await socialAction(e,'/api/social/mode',{mode:'active'});await socialTick(e,new Date(due-1200000));assert.equal(calls,1);assert.equal(e.db.prepare('SELECT status FROM social_jobs').get().status,'processing');}finally{globalThis.fetch=f;}});
test('同時実行でも公開は一回のみ、公開結果とリンクを保存',async()=>{const e=env();active(e);await socialAction(e,'/api/social/queue',payload(),now);e.db.prepare("UPDATE social_jobs SET status='ready',container_id='c'").run();let published=0;const f=globalThis.fetch;globalThis.fetch=async(url,options)=>{if(options.method==='POST'){published++;return Response.json({id:'media'});}return Response.json({permalink:'https://www.instagram.com/p/test/'});};try{await Promise.all([socialTick(e,new Date(due)),socialTick(e,new Date(due))]);await socialTick(e,new Date(due+300000));assert.equal(published,1);const j=e.db.prepare('SELECT * FROM social_jobs').get();assert.equal(j.status,'published');assert.equal(j.media_id,'media');assert.equal(j.permalink,'https://www.instagram.com/p/test/');}finally{globalThis.fetch=f;}});
test('公開通信が途切れたとき再送せず、遅延超過も停止する',async()=>{const e=env();active(e);await socialAction(e,'/api/social/queue',payload(),now);e.db.prepare("UPDATE social_jobs SET status='ready',container_id='c'").run();let attempts=0;const f=globalThis.fetch;globalThis.fetch=async()=>{attempts++;throw Error('timeout');};try{await socialTick(e,new Date(due));await socialTick(e,new Date(due+300000));assert.equal(attempts,1);assert.equal(e.db.prepare('SELECT status FROM social_jobs').get().status,'uncertain');await assert.rejects(()=>socialAction(e,'/api/social/cancel',{id:e.db.prepare('SELECT id FROM social_jobs').get().id}));}finally{globalThis.fetch=f;}const e2=env();active(e2);await socialAction(e2,'/api/social/queue',payload(),now);await socialTick(e2,new Date(due+91*60000));assert.equal(e2.db.prepare('SELECT status FROM social_jobs').get().status,'failed');});
test('途中終了の公開処理は確認待ちにして再公開しない',async()=>{const e=env();active(e);await socialAction(e,'/api/social/queue',payload(),now);e.db.prepare("UPDATE social_jobs SET status='publishing',updated=?").run(now);await socialTick(e,new Date(due));assert.equal(e.db.prepare('SELECT status FROM social_jobs').get().status,'uncertain');});
test('管理APIは所有者認証・同一サイト・HTTP操作種別を検証',async()=>{const e=env();const req=(path,method='GET',body,headers={})=>new Request(e.APP_ORIGIN+path,{method,headers:{Origin:e.APP_ORIGIN,...headers},body:body?JSON.stringify(body):undefined});assert.equal((await worker.fetch(req('/api/social/status'),e)).status,401);const login=await worker.fetch(req('/api/login','POST',{password:'owner'}),e);const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await worker.fetch(req('/api/social/status','GET',undefined,{Cookie:cookie}),e)).status,200);assert.equal((await worker.fetch(req('/api/social/mode','POST',{mode:'active'},{Cookie:cookie,Origin:'https://evil.test'}),e)).status,403);assert.equal((await worker.fetch(req('/api/social/mode','GET',undefined,{Cookie:cookie}),e)).status,405);});
